module.exports = [
  "guilded.gg",
  "guilded",
  "rocket league",
  "fortnite",
  "witch it",
  "valorant",
  "bluestacks x",
  "bluestacks",
  "minecraft",
  "forza horizon 5",
  "forza horizon 4",
  "forza horizon 3",
  "forza horizon 2",
  "forza horizon 1",
  "forza horizon",
  "visual studio code",
  "visual studio",
  "atom",
  "sublime text",
  "adobe illustrator",
  "adobe photoshop",
  "adobe xd",
  "adobe dimension",
  "adobe after effects",
  "vim",
  "neovim",
  "blender",
  "autodesk 3ds max",
  "aseprite",
  "intellij idea ultimate",
  "intellij idea community",
  "phpstorm",
  "jetbrains ide",
  "youtube music",
];
