module.exports = [
  "ableton live",
  "adobe acrobat",
  "adobe after effects",
  "adobe audition",
  "adobe dimension",
  "adobe illustrator",
  "adobe photoshop",
  "adobe premiere pro",
  "adobe xd",
  "among us",
  "animal crossing: new horizons",
  "apex legends",
  "ark: survival evolved",
  "aseprite",
  "assassin's creed Valhalla",
  "atom",
  "autodesk 3ds max",
  "autocad",
  "blender",
  "bluestacks",
  "bluestacks x",
  "borderlands 3",
  "call of duty: warzone",
  "civilization VI",
  "counter-strike: global offensive",
  "cubase",
  "cyberpunk 2077",
  "dead by daylight",
  "dead cells",
  "destiny 2",
  "diablo III",
  "discord",
  "doom eternal",
  "dota 2",
  "fall guys",
  "fallout 4",
  "final fantasy XIV",
  "fleet",
  "for honor",
  "forza horizon",
  "forza horizon 1",
  "forza horizon 2",
  "forza horizon 3",
  "forza horizon 4",
  "forza horizon 5",
  "fortnite",
  "garry's mod",
  "google chrome",
  "google docs",
  "google sheets",
  "google slides",
  "google meet",
  "grand theft auto V",
  "guilded",
  "guilded.gg",
  "hearthstone",
  "heroes of the storm",
  "intellij idea community",
  "intellij idea ultimate",
  "league of legends",
  "last.fm",
  "lastfm",
  "logic pro",
  "mario kart 8 deluxe",
  "microsoft excel",
  "microsoft office",
  "microsoft powerpoint",
  "microsoft word",
  "minecraft",
  "monster hunter: world",
  "neovim",
  "overwatch",
  "phasmophobia",
  "phpstorm",
  "playerunknown's battlegrounds",
  "pokemon sword and shield",
  "pro tools",
  "premid",
  "rainbow six siege",
  "red dead redemption 2",
  "rocket league",
  "sea of thieves",
  "serato dj",
  "skype",
  "slack",
  "smite",
  "solidworks",
  "sony vegas pro",
  "splatoon 2",
  "spotify",
  "starcraft II",
  "sublime text",
  "super smash bros. ultimate",
  "terraria",
  "the elder scrolls online",
  "the legend of zelda: breath of the wild",
  "the sims 4",
  "trello",
  "twitch",
  "valorant",
  "vim",
  "virtual dj",
  "visual studio",
  "visual studio code",
  "warframe",
  "webstorm",
  "whatsapp",
  "witch it",
  "world of tanks",
  "world of warcraft",
  "youtube music",
  "zoom"
];
